"""add editorial workflow states

Revision ID: 74818eecb0e8
Revises: b6ff3e4aaae7
Create Date: 2026-08-12 23:07:58.900300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74818eecb0e8'
down_revision: Union[str, None] = 'b6ff3e4aaae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content_items', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))

    op.execute(
        "UPDATE content_items SET status = 'in_review' WHERE status = 'draft';"
    )
    op.execute(
        "UPDATE content_items SET status = 'ready' WHERE status = 'approved';"
    )
    op.execute(
        "UPDATE content_items SET status = 'archived' WHERE status = 'rejected';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'due_date')
    op.drop_table('status_history')
    # ### end Alembic commands ###
